### PR TITLE
Bump types version

### PR DESCRIPTION
**Pull request by jgonet**
Bumping TS types to include changes in the TS repo:
- [[hammerjs] Add missing event data](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50438)
- [[hammerjs] Use number literals in constants](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50433)

Unmerged PRs: [[hammerjs] Use literal types for `eventType`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50966)

I upgraded locally and the node still uses .36 version though the caret pin should be compatible with it, not sure why.

### CODE REVIEW

**Comment by WoodNeck** [comment]
Hello @jakub-gonet! Thanks for the PR!

@daybrush @mixed 
I wonder why `@types/hammerjs` is included as our dependencies, doesn't it have to be in the devDependencies?
I found out that fc3cd96 added it.

**Comment by mixed** [comment]
I agree with you.

**Comment by daybrush** [comment]
If the type is supported by default, dependencies

If the type is not supported by default, we can add it to devDependencies.

The reason we put the dependency is because it import from hammer.d.ts.

**Review by daybrush — APPROVED** [review]

**Review by WoodNeck — APPROVED** [review]
@daybrush 
So that's why, I hope we don't require any further dependency version update like this though...

**Comment by daybrush** [comment]
@jakub-gonet 

It seems that the version of the type has been updated recently.
If you want to use the updated type, delete `@egjs/hammerjs` and reinstall or install the latest version of `@types/hammerjs`.


@WoodNeck 

right. It's just a package-lock issue, so there seems to be no reason for us to update it separately.

**Comment by jgonet** [comment]
That's a quick response, thanks 😄 

Seems like it actually was a lock issue, after regenerating yarn.lock, it correctly resolved `.36` to `.38`:
```diff
@@ -2116,11 +1594,7 @@
   dependencies:
     "@types/node" "*"

-"@types/hammerjs@^2.0.36":
-  version "2.0.36"
-  resolved "https://registry.yarnpkg.com/@types/hammerjs/-/hammerjs-2.0.36.tgz#17ce0a235e9ffbcdcdf5095646b374c2bf615a4c"
-
-"@types/hammerjs@^2.0.38":
+"@types/hammerjs@^2.0.36", "@types/hammerjs@^2.0.38":
   version "2.0.38"
   resolved "https://registry.yarnpkg.com/@types/hammerjs/-/hammerjs-2.0.38.tgz#44fdab66fb960fc7002f4a9e54d91545f0bf9448"
   integrity sha512-wuwDzWW1JWh3BZoRftBlKcctjNzR75QFY4/b4zAz7sH1EesA8HBJzke+bF5dxCATNdHHs3X1P5UWanbbUT6chw==
@@ -2136,24 +1610,29 @@
```

Before submitting I updated types and removed hammerjs from node-modules, reinstalling them with `yarn install --check-files`, seems like this doesn't update packages that depend on it, oh well.

Sorry for bothering you in that case.

BTW, you import TS types only to be compatible with the original hammerjs types? I'm asking because you could fairly easily migrate off DefinitelyTyped.

**Comment by daybrush** [comment]
@jakub-gonet

Thank you :)

Yes. We can't just use `@types/hammerjs` because we have `@egjs`.

So, to support `@egjs/hammerjs` type, `@types/hammerjs` was imported.

**Pull request closed without merging**
